### ISSUE TITLE
Great Plugin! Needs more customability *Not issue*

### ISSUE THREAD

**Issue by Vodkafroggie101** [Mohagames205/RGBArmor#1]
it does not let you choose what type of armor you want it only gives you leather, if you could change it so it gives you diamond armor instead, that would be great!

**Comment by TheDataLioness** [comment]
I mean yea for sure that makes a lot of sense.
I want pink Diamond Armor because that's an actual thing in Minecraft.
Dyeing leather armor is an actual Minecraft feature you can't just color any armor you want.
You want RGB Diamond Armour?
Get Protection 100 on it and give it the RGB Color: 135,206,235
Because that is almost the same color as actual Diamond Armour.

**Comment by Mohagames205** [comment]
Closing this issue because it's impossible to implement.
